-- Neo-tree is a Neovim plugin to browse the file system
-- https://github.com/nvim-neo-tree/neo-tree.nvim

-- return {
--   'nvim-neo-tree/neo-tree.nvim',
--   version = '*',
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
--     'MunifTanjim/nui.nvim',
--   },
--   lazy = false,
--   keys = {
--     --{ '\\', ':Neotree reveal<CR>', desc = 'NeoTree reveal', silent = true },
--   },
--   opts = {
--     filesystem = {
--       use_libuv_file_watcher = true,
--       filtered_items = {
--         visible = false, -- hide filtered items on open
--         hide_gitignored = false,
--         hide_dotfiles = false, -- Do not hide dotfiles (e.g., .git, .config)
--       },
--       gitignored = false,
--       window = {
--         mappings = {
--           --['\\'] = 'close_window',
--         },
--       },
--     },
--   },
-- }
